### PR TITLE
Sona Abrahamyan

### PR DESCRIPTION
**Pull request by SonaAbrahamyan**
Completed PDP tasks

### CODE REVIEW

**Comment by arayik-chaparyan** [comment]
> Created collection via Postman, which could not upload as that file type is not supported.

Sona jan thank you for results. Could you please, as a result of first task, push commit collection and keywords files to be able to import into PostMan and run collection with tests.

**Comment by arayik-chaparyan** [comment]
Thank you Sona jan. It is working. But do you really need all query parameters and all headers in requests. Can you please minimize query parameters and headers and provide solution again.
THanks

**Comment by SonaAbrahamyan** [comment]
Hi Arayik. Pushed the updated Postman collection with minimized query parameters and headers.
Thanks.

**Comment by arayik-chaparyan** [comment]
Sona jan still there are extra query and header parameters. 
Please try to remove parameters which are not affecting on result and commit again.
Thanks

**Comment by SonaAbrahamyan** [comment]
Arayik jan, don't know exactly which query and header parameters are extra as I import the curl from the site. Can you please point me in the right direction? 

However, removed some parameters and added the optimized version. Please have a look.
Thanks.

**Comment by arayik-chaparyan** [comment]
Sona jan I think only parameter "q" is enough (without any header parameter) to make those requests successfuly.
Thanks

**Comment by SonaAbrahamyan** [comment]
Arayik jan, thank you for pointing me. Made requests only with "q" parameter successfully.

**Comment by arayik-chaparyan** [comment]
Thank you Sona jan. Looks good.

**Pull request closed without merging**
