### PR TITLE
PDP tasks solutions from Garegin Adunts

### PR DESCRIPTION
**Pull request by aduntsgaregin**
Hi Arayik,

On this branch are my PDP completed tasks. 

Will be waiting for your review and comments.

Regards,
Garegin

### CODE REVIEW

**Comment by arayik-chaparyan** [comment]
Hi Garegin jan,

thank you for results

Can you please join into one collection
- to get search keywords from external files
- to get search engines from env variables

**Comment by aduntsgaregin** [comment]
Hi Arayik,

Thank you for your consideration. Could you, please kindly clarify as seems both requests are in one collection or maybe I don't understand you correctly?

**Comment by arayik-chaparyan** [comment]
Sure, I mean to have one request but cover both tasks.
If more info needed - lets talk in skype

**Comment by aduntsgaregin** [comment]
Hi Arayik, I have made the changes and updated the task
Please review when you have a chance.
Regards,
Garegin

**Comment by arayik-chaparyan** [comment]
Thank you Garegin jan,

All looks good.

**Pull request closed without merging**
