### PR TITLE
Arshak Hayriyan

### PR DESCRIPTION
**Pull request by arshakhayryan**
Please review the PDP tasks that have been completed.

Regards
Arshak

### CODE REVIEW

**Comment by arayik-chaparyan** [comment]
Arshak jan thank you

Seems you have missed data file for cities

**Comment by arayik-chaparyan** [comment]
Also, can you make collection such as we can able to select search engine from env field and make tests run against it.

Thank you

**Comment by arshakhayryan** [comment]
I have updated postman task solution,please review.

Regards Arshak

**Comment by arayik-chaparyan** [comment]
Thank you Arshak jan.

Looks good to me.

Note: those tasks are just examples, so please go fwd with mentioned tools knowledge and more & more experiments.

**Pull request closed without merging**
