### PR TITLE
pdp tasks Anush Avanesyan

### PR DESCRIPTION
**Pull request by shunna87**
Here are my pdp task solutions.
Please review.
Regards, Anush Avanesyan

### CODE REVIEW

**Comment by arayik-chaparyan** [comment]
Thank you Anush jan
Seems your env file is not correct. Can you please re - check ?

**Comment by shunna87** [comment]
Changed

**Comment by shunna87** [comment]
Edited Env file

**Comment by arayik-chaparyan** [comment]
Thank you Anush jan,

The provided files works on my side but I noticed some extra info/data in that:
 - environment contains "city" variable with value "6"
 - request body contains - { "username": "{{username}}"}

**Comment by shunna87** [comment]
Thank you very much :) just removed extra texts

**Comment by arayik-chaparyan** [comment]
THank you !

Anush jan, those are just small examples and you need to continue explore tools and functionalities related to this tasks.

**Pull request closed without merging**
