### PR TITLE
Added PDP tasks.

### PR DESCRIPTION
**Pull request by Kristina-github**
Please, review my PDP tasks.

### CODE REVIEW

**Comment by arayik-chaparyan** [comment]
Thank you Kristina jan. Could you please minimize url query parameters and push again? Thanks

**Comment by arayik-chaparyan** [comment]
Thanks Kristina jan.
Could you please optimize also query paramateres?
THanks

**Comment by arayik-chaparyan** [comment]
Kristina jan now I can't see any file. I think you have deleted and commited all your files.

**Comment by Kristina-github** [comment]
Sorry, I pushed that by mistake.
Please, review the new changes.

Thanks

**Comment by arayik-chaparyan** [comment]
Perfect. All looks good. Thank you

**Pull request closed without merging**
