### PR TITLE
PDP_Task_Solutions

### PR DESCRIPTION
**Pull request by NarekTelunts21**

### CODE REVIEW

**Comment by NarekTelunts21** [comment]
PDP_Task_Solutions

**Comment by NarekTelunts21** [comment]
Narek_Telunts

**Comment by NarekTelunts21** [comment]
Narek_Telunts

**Comment by arayik-chaparyan** [comment]
Hi Narek jan,

Thank you for results.
Could you please add text files to be able to easy use - for postman collection and data files if any.

**Comment by NarekTelunts21** [comment]
Hi Arayik jan,

I have added Postman files

**Pull request closed without merging**
