### PR TITLE
Mariam Martirosyan

### PR DESCRIPTION
**Pull request by mariammartirosyan94**
Hi Arayik!
I have completed PDP Tools support task.
Please review.

With regards
Mariam.

### CODE REVIEW

**Comment by arayik-chaparyan** [comment]
Thank you Mariam jan,

Some issues I saw:

Collection file contains 2 requests:
 - with hardcoded search engine "https://search.yahoo.com/search?p={{city}}"
 - with hardcoded city value "{{base_url}}?{{key}}=goris"
 
 "Env1" environment contains "city" variable which is needed to be loaded from external data file but not environment file
 
 "Bing" env file contains URL with "?" end symbol but collection assumes "?" to be added in collection rather than in env variable
 
 Please have a look on those issues, fix them, cleanup and let me know to review again.

**Comment by mariammartirosyan94** [comment]
Hi Arayik jan.
Added fixes, please review, thank you.

**Comment by arayik-chaparyan** [comment]
Thank you Mariam jan,

One more request - can you please join to requests into one to:
 - have search key works from external file
 - have search engines from environment variables
 
 Thanks

**Comment by mariammartirosyan94** [comment]
Hi Arayik jan.
Made requested changes, please review.
Thank you

**Comment by arayik-chaparyan** [comment]
Thank you Mariam jan.
Looks good.

**Comment by arayik-chaparyan** [comment]
Please note that this is just an example for simple tasks - so, please constantly continue exploring all tools and technologies related to work and QA in general.

**Pull request closed without merging**
